CREATE DATABASE IF NOT EXISTS parcoursup2;
USE parcoursup2;
CREATE TABLE IF NOT EXISTS departement (
	dep VARCHAR(4),
	dep_lib VARCHAR(32),
	region_etab_aff VARCHAR(32),
	academies VARCHAR(32) NOT NULL,
	PRIMARY KEY (dep)
);
CREATE TABLE IF NOT EXISTS etablissement (
	cod_uai CHAR(8) NOT NULL,
	contrat_etab VARCHAR(32) NOT NULL,
	g_ea_lib_vx VARCHAR(255) NOT NULL,
	dep VARCHAR(4),
	ville_etab VARCHAR(32) NOT NULL,
	etablissement_id_paysage CHAR(5),
	PRIMARY KEY (cod_uai),
	FOREIGN KEY (dep) REFERENCES departement(dep)
);
CREATE TABLE IF NOT EXISTS formation (
	cod_aff_form INT NOT NULL CHECK (cod_aff_form >= 0),
	cod_uai CHAR(8) NOT NULL,
	lib_for_voe_ins TEXT NOT NULL,
	select_form VARCHAR(32) NOT NULL,
	fili VARCHAR(32) NOT NULL,
	lib_comp_voe_ins TEXT NOT NULL,
	form_lib_voe_acc VARCHAR(128) NOT NULL,
	fil_lib_voe_acc VARCHAR(255) NOT NULL,
	detail_forma VARCHAR(255),
	geolocalisation_des_formations_lon FLOAT,
	geolocalisation_des_formations_lat FLOAT,
	list_com VARCHAR(64) NOT NULL,
	tri VARCHAR(32) NOT NULL,
	detail_forma2 VARCHAR(128),
	lien_form_psup VARCHAR(128),
	composante_id_paysage CHAR(5),
	PRIMARY KEY (cod_aff_form),
	FOREIGN KEY (cod_uai) REFERENCES etablissement(cod_uai)
);
CREATE TABLE IF NOT EXISTS statistiques (
	session SMALLINT NOT NULL CHECK (session >= 0),
	cod_aff_form INT NOT NULL CHECK (cod_aff_form >= 0),
	capa_fin SMALLINT NOT NULL CHECK (capa_fin >= 0),
	voe_tot SMALLINT NOT NULL CHECK (voe_tot >= 0),
	voe_tot_f SMALLINT NOT NULL CHECK (voe_tot_f >= 0),
	nb_voe_pp SMALLINT NOT NULL CHECK (nb_voe_pp >= 0),
	nb_voe_pp_internat SMALLINT CHECK (nb_voe_pp_internat >= 0),
	nb_voe_pp_bg SMALLINT NOT NULL CHECK (nb_voe_pp_bg >= 0),
	nb_voe_pp_bg_brs SMALLINT NOT NULL CHECK (nb_voe_pp_bg_brs >= 0),
	nb_voe_pp_bt SMALLINT NOT NULL CHECK (nb_voe_pp_bt >= 0),
	nb_voe_pp_bt_brs SMALLINT NOT NULL CHECK (nb_voe_pp_bt_brs >= 0),
	nb_voe_pp_bp SMALLINT NOT NULL CHECK (nb_voe_pp_bp >= 0),
	nb_voe_pp_bp_brs SMALLINT NOT NULL CHECK (nb_voe_pp_bp_brs >= 0),
	nb_voe_pp_at SMALLINT NOT NULL CHECK (nb_voe_pp_at >= 0),
	nb_voe_pc SMALLINT NOT NULL CHECK (nb_voe_pc >= 0),
	nb_voe_pc_bg SMALLINT NOT NULL CHECK (nb_voe_pc_bg >= 0),
	nb_voe_pc_bt SMALLINT NOT NULL CHECK (nb_voe_pc_bt >= 0),
	nb_voe_pc_bp SMALLINT NOT NULL CHECK (nb_voe_pc_bp >= 0),
	nb_voe_pc_at SMALLINT NOT NULL CHECK (nb_voe_pc_at >= 0),
	nb_cla_pp SMALLINT NOT NULL CHECK (nb_cla_pp >= 0),
	nb_cla_pc SMALLINT NOT NULL CHECK (nb_cla_pc >= 0),
	nb_cla_pp_internat SMALLINT CHECK (nb_cla_pp_internat >= 0),
	nb_cla_pp_pasinternat SMALLINT CHECK (nb_cla_pp_pasinternat >= 0),
	nb_cla_pp_bg SMALLINT NOT NULL CHECK (nb_cla_pp_bg >= 0),
	nb_cla_pp_bg_brs SMALLINT NOT NULL CHECK (nb_cla_pp_bg_brs >= 0),
	nb_cla_pp_bt SMALLINT NOT NULL CHECK (nb_cla_pp_bt >= 0),
	nb_cla_pp_bt_brs SMALLINT NOT NULL CHECK (nb_cla_pp_bt_brs >= 0),
	nb_cla_pp_bp SMALLINT NOT NULL CHECK (nb_cla_pp_bp >= 0),
	nb_cla_pp_bp_brs SMALLINT NOT NULL CHECK (nb_cla_pp_bp_brs >= 0),
	nb_cla_pp_at SMALLINT NOT NULL CHECK (nb_cla_pp_at >= 0),
	prop_tot SMALLINT NOT NULL CHECK (prop_tot >= 0),
	acc_tot SMALLINT NOT NULL CHECK (acc_tot >= 0),
	acc_tot_f SMALLINT NOT NULL CHECK (acc_tot_f >= 0),
	acc_pp SMALLINT NOT NULL CHECK (acc_pp >= 0),
	acc_pc SMALLINT NOT NULL CHECK (acc_pc >= 0),
	acc_debutpp SMALLINT NOT NULL CHECK (acc_debutpp >= 0),
	acc_datebac SMALLINT NOT NULL CHECK (acc_datebac >= 0),
	acc_finpp SMALLINT NOT NULL CHECK (acc_finpp >= 0),
	acc_internat SMALLINT CHECK (acc_internat >= 0),
	acc_brs SMALLINT NOT NULL CHECK (acc_brs >= 0),
	acc_neobac SMALLINT NOT NULL CHECK (acc_neobac >= 0),
	acc_bg SMALLINT NOT NULL CHECK (acc_bg >= 0),
	acc_bt SMALLINT NOT NULL CHECK (acc_bt >= 0),
	acc_bp SMALLINT NOT NULL CHECK (acc_bp >= 0),
	acc_at SMALLINT NOT NULL CHECK (acc_at >= 0),
	acc_mention_nonrenseignee TINYINT NOT NULL CHECK (acc_mention_nonrenseignee >= 0 AND acc_mention_nonrenseignee <= 100),
	acc_sansmention SMALLINT NOT NULL CHECK (acc_sansmention >= 0),
	acc_ab SMALLINT NOT NULL CHECK (acc_ab >= 0),
	acc_b SMALLINT NOT NULL CHECK (acc_b >= 0),
	acc_tb SMALLINT NOT NULL CHECK (acc_tb >= 0),
	acc_tbf SMALLINT NOT NULL CHECK (acc_tbf >= 0),
	acc_bg_mention SMALLINT NOT NULL CHECK (acc_bg_mention >= 0),
	acc_bt_mention SMALLINT NOT NULL CHECK (acc_bt_mention >= 0),
	acc_bp_mention TINYINT NOT NULL CHECK (acc_bp_mention >= 0 AND acc_bp_mention <= 100),
	acc_term TINYINT CHECK (acc_term >= 0 AND acc_term <= 100),
	acc_term_f TINYINT CHECK (acc_term_f >= 0 AND acc_term_f <= 100),
	acc_aca_orig SMALLINT NOT NULL CHECK (acc_aca_orig >= 0),
	acc_aca_orig_idf SMALLINT NOT NULL CHECK (acc_aca_orig_idf >= 0),
	pct_acc_debutpp TINYINT NOT NULL CHECK (pct_acc_debutpp >= 0 AND pct_acc_debutpp <= 100),
	pct_acc_datebac TINYINT NOT NULL CHECK (pct_acc_datebac >= 0 AND pct_acc_datebac <= 100),
	pct_acc_finpp TINYINT NOT NULL CHECK (pct_acc_finpp >= 0 AND pct_acc_finpp <= 100),
	pct_f TINYINT NOT NULL CHECK (pct_f >= 0 AND pct_f <= 100),
	pct_aca_orig TINYINT NOT NULL CHECK (pct_aca_orig >= 0 AND pct_aca_orig <= 100),
	pct_aca_orig_idf TINYINT NOT NULL CHECK (pct_aca_orig_idf >= 0 AND pct_aca_orig_idf <= 100),
	pct_etab_orig TINYINT CHECK (pct_etab_orig >= 0 AND pct_etab_orig <= 100),
	pct_bours TINYINT NOT NULL CHECK (pct_bours >= 0 AND pct_bours <= 100),
	pct_neobac TINYINT NOT NULL CHECK (pct_neobac >= 0 AND pct_neobac <= 100),
	pct_mention_nonrenseignee TINYINT NOT NULL CHECK (pct_mention_nonrenseignee >= 0 AND pct_mention_nonrenseignee <= 100),
	pct_sansmention TINYINT NOT NULL CHECK (pct_sansmention >= 0 AND pct_sansmention <= 100),
	pct_ab TINYINT NOT NULL CHECK (pct_ab >= 0 AND pct_ab <= 100),
	pct_b TINYINT NOT NULL CHECK (pct_b >= 0 AND pct_b <= 100),
	pct_tb TINYINT NOT NULL CHECK (pct_tb >= 0 AND pct_tb <= 100),
	pct_tbf TINYINT NOT NULL CHECK (pct_tbf >= 0 AND pct_tbf <= 100),
	pct_bg TINYINT NOT NULL CHECK (pct_bg >= 0 AND pct_bg <= 100),
	pct_bg_mention TINYINT NOT NULL CHECK (pct_bg_mention >= 0 AND pct_bg_mention <= 100),
	pct_bt TINYINT NOT NULL CHECK (pct_bt >= 0 AND pct_bt <= 100),
	pct_bt_mention TINYINT NOT NULL CHECK (pct_bt_mention >= 0 AND pct_bt_mention <= 100),
	pct_bp TINYINT NOT NULL CHECK (pct_bp >= 0 AND pct_bp <= 100),
	pct_bp_mention TINYINT NOT NULL CHECK (pct_bp_mention >= 0 AND pct_bp_mention <= 100),
	prop_tot_bg SMALLINT NOT NULL CHECK (prop_tot_bg >= 0),
	prop_tot_bg_brs SMALLINT NOT NULL CHECK (prop_tot_bg_brs >= 0),
	prop_tot_bt SMALLINT NOT NULL CHECK (prop_tot_bt >= 0),
	prop_tot_bt_brs SMALLINT NOT NULL CHECK (prop_tot_bt_brs >= 0),
	prop_tot_bp SMALLINT NOT NULL CHECK (prop_tot_bp >= 0),
	prop_tot_bp_brs SMALLINT NOT NULL CHECK (prop_tot_bp_brs >= 0),
	prop_tot_at SMALLINT NOT NULL CHECK (prop_tot_at >= 0),
	lib_grp1 VARCHAR(128),
	ran_grp1 VARCHAR(8),
	lib_grp2 VARCHAR(64),
	ran_grp2 SMALLINT CHECK (ran_grp2 >= 0),
	lib_grp3 VARCHAR(64),
	ran_grp3 SMALLINT CHECK (ran_grp3 >= 0),
	taux_acces_ens VARCHAR(4),
	part_acces_gen VARCHAR(4),
	part_acces_tec VARCHAR(4),
	part_acces_pro VARCHAR(4),
	PRIMARY KEY (session, cod_aff_form),
	FOREIGN KEY (cod_aff_form) REFERENCES formation(cod_aff_form)
);
INSERT INTO
	departement
SELECT
	DISTINCT dep,
	dep_lib,
	region_etab_aff,
	academies
FROM
	parcoursup.parcoursup
WHERE
	dep IS NOT NULL;
INSERT INTO
	etablissement
SELECT
	DISTINCT cod_uai,
	contrat_etab,
	g_ea_lib_vx,
	dep,
	ville_etab,
	etablissement_id_paysage
FROM
	parcoursup.parcoursup;
INSERT INTO
	formation
SELECT
	DISTINCT cod_aff_form,
	cod_uai,
	lib_for_voe_ins,
	select_form,
	fili,
	lib_comp_voe_ins,
	form_lib_voe_acc,
	fil_lib_voe_acc,
	detail_forma,
	geolocalisation_des_formations_lon,
	geolocalisation_des_formations_lat,
	list_com,
	tri,
	detail_forma2,
	lien_form_psup,
	composante_id_paysage
FROM
	parcoursup.parcoursup;
INSERT INTO
	statistiques
SELECT
	DISTINCT session,
	cod_aff_form,
	capa_fin,
	voe_tot,
	voe_tot_f,
	nb_voe_pp,
	nb_voe_pp_internat,
	nb_voe_pp_bg,
	nb_voe_pp_bg_brs,
	nb_voe_pp_bt,
	nb_voe_pp_bt_brs,
	nb_voe_pp_bp,
	nb_voe_pp_bp_brs,
	nb_voe_pp_at,
	nb_voe_pc,
	nb_voe_pc_bg,
	nb_voe_pc_bt,
	nb_voe_pc_bp,
	nb_voe_pc_at,
	nb_cla_pp,
	nb_cla_pc,
	nb_cla_pp_internat,
	nb_cla_pp_pasinternat,
	nb_cla_pp_bg,
	nb_cla_pp_bg_brs,
	nb_cla_pp_bt,
	nb_cla_pp_bt_brs,
	nb_cla_pp_bp,
	nb_cla_pp_bp_brs,
	nb_cla_pp_at,
	prop_tot,
	acc_tot,
	acc_tot_f,
	acc_pp,
	acc_pc,
	acc_debutpp,
	acc_datebac,
	acc_finpp,
	acc_internat,
	acc_brs,
	acc_neobac,
	acc_bg,
	acc_bt,
	acc_bp,
	acc_at,
	acc_mention_nonrenseignee,
	acc_sansmention,
	acc_ab,
	acc_b,
	acc_tb,
	acc_tbf,
	acc_bg_mention,
	acc_bt_mention,
	acc_bp_mention,
	acc_term,
	acc_term_f,
	acc_aca_orig,
	acc_aca_orig_idf,
	pct_acc_debutpp,
	pct_acc_datebac,
	pct_acc_finpp,
	pct_f,
	pct_aca_orig,
	pct_aca_orig_idf,
	pct_etab_orig,
	pct_bours,
	pct_neobac,
	pct_mention_nonrenseignee,
	pct_sansmention,
	pct_ab,
	pct_b,
	pct_tb,
	pct_tbf,
	pct_bg,
	pct_bg_mention,
	pct_bt,
	pct_bt_mention,
	pct_bp,
	pct_bp_mention,
	prop_tot_bg,
	prop_tot_bg_brs,
	prop_tot_bt,
	prop_tot_bt_brs,
	prop_tot_bp,
	prop_tot_bp_brs,
	prop_tot_at,
	lib_grp1,
	ran_grp1,
	lib_grp2,
	ran_grp2,
	lib_grp3,
	ran_grp3,
	taux_acces_ens,
	part_acces_gen,
	part_acces_tec,
	part_acces_pro
FROM
	parcoursup.parcoursup;